//
//  GlobalConst.swift
//  project
//
//  Created by Nixforest on 9/5/16.
//  Copyright © 2016 admin. All rights reserved.
//

import Foundation
class GlobalConst {
    static let CONTENT00001 = "Harpy Framework"
    static let CONTENT00002 = "Chưa chọn khách hàng"
    static let CONTENT00003 = "Chưa chọn nguyên nhân!"
    static let CONTENT00004 = "Chưa nhập tiêu đề!"
    static let CONTENT00005 = "Chưa nhập nội dung!"
    static let CONTENT00006 = "Bạn chỉ được nhập tối đa %1$d hình!"
    static let CONTENT00007 = "Vui lòng kiểm tra lại dữ liệu!"
    static let CONTENT00008 = "OK"
    static let CONTENT00009 = "Cancel"
    static let CONTENT00010 = "Bạn chắc chắn muốn close Issue"
    static let CONTENT00011 = "Bạn chắc chắn muốn Reopen Issue"
    static let CONTENT00012 = "Mã số:"
    static let CONTENT00013 = "Khách hàng:"
    static let CONTENT00014 = "NV kinh doanh:"
    static let CONTENT00015 = "Địa chỉ:"
    static let CONTENT00016 = "Tiêu đề:"
    static let CONTENT00017 = "Người tạo:"
    static let CONTENT00018 = "Ngày tạo:"
    static let CONTENT00019 = "Trạng thái:"
    static let CONTENT00020 = "Nguyên nhân:"
    static let CONTENT00021 = "Điện thoại:"
    static let CONTENT00022 = "Người liên hệ:"
    static let CONTENT00023 = "Tài khoản và mật khẩu không được trống!"
    static let CONTENT00024 = "(%1$s)"
    static let CONTENT00025 = "Bạn vui lòng điền đầy đủ thông tin!"
    static let CONTENT00026 = "Mật khẩu nhập lại không chính xác!"
    static let CONTENT00027 = "Chưa chọn NV bảo trì!"
    static let CONTENT00028 = "Chưa chọn loại sự cố!"
    static let CONTENT00029 = "Chưa nhập người liên hệ!"
    static let CONTENT00030 = "Chưa nhập số điện thoại!"
    static let CONTENT00031 = "Nội dung: \n"
    static let CONTENT00032 = "Liên hệ:"
    static let CONTENT00033 = "Sự cố:"
    static let CONTENT00034 = "Mức độ:"
    static let CONTENT00035 = "Ngày bảo trì:"
    static let CONTENT00036 = "Lịch bảo trì:"
    static let CONTENT00037 = "Nhân viên bảo trì:"
    static let CONTENT00038 = "Số điện thoại:"
    static let CONTENT00039 = "Báo cáo kết quả: \n"
    static let CONTENT00040 = "Bảo trì định kỳ"
    static let CONTENT00041 = "Yêu cầu bảo trì"
    static let CONTENT00042 = "Thời gian xử lý:"
    static let CONTENT00043 = "Chưa chọn trạng thái!"
    static let CONTENT00044 = "Tin nhắn từ Gas Service"
    static let CONTENT00045 = "Nội dung:"
    static let CONTENT00046 = "Mất kết nối mạng, vui lòng thử lại!"
    static let CONTENT00047 = "Có lỗi xảy ra, vui lòng thử lại!"
    static let CONTENT00048 = "Có lỗi xảy ra"
    static let CONTENT00049 = "Tài khoản / Số điện thoại"
    static let CONTENT00050 = "Mật khẩu"
    static let CONTENT00051 = "Đăng nhập"
    static let CONTENT00052 = "Đăng ký"
    static let CONTENT00053 = "Welcome to gas app!"
    static let CONTENT00054 = "Số điện thoại"
    static let CONTENT00055 = "Họ và tên"
    static let CONTENT00056 = "Nhập lại mật khẩu"
    static let CONTENT00057 = "Số nhà"
    static let CONTENT00058 = "Tên đường"
    static let CONTENT00059 = "Title"
    static let CONTENT00060 = "Tìm kiếm KH, nhập tối thiểu 5 ký tự"
    static let CONTENT00061 = "Mã khách hàng"
    static let CONTENT00062 = "Tiêu đề"
    static let CONTENT00063 = "Nội dung"
    static let CONTENT00064 = "Thêm hình"
    static let CONTENT00065 = "Tạo mới"
    static let CONTENT00066 = "Xoá hình"
    static let CONTENT00067 = "Open"
    static let CONTENT00068 = "Close"
    static let CONTENT00069 = "Không có dữ liệu"
    static let CONTENT00070 = "Gửi trả lời"
    static let CONTENT00072 = "Thông tin"
    static let CONTENT00073 = "Đóng lại"
    static let CONTENT00074 = "Mới"
    static let CONTENT00075 = "Đã xem"
    static let CONTENT00076 = "Người liên hệ"
    static let CONTENT00077 = "Bảo trì sự cố"
    static let CONTENT00078 = "Bảo trì định kỳ"
    static let CONTENT00079 = "Tên khách hàng"
    static let CONTENT00080 = "Báo sai sự cố"
    static let CONTENT00081 = "Ghi chú"
    static let CONTENT00082 = "Ghi chú nội bộ"
    static let CONTENT00083 = "Mật khẩu cũ"
    static let CONTENT00084 = "Mật khẩu mới"
    static let CONTENT00085 = "Xác nhận mật khẩu mới"
    static let CONTENT00086 = "Lưu"
    static let CONTENT00087 = "Họ tên"
    static let CONTENT00088 = "Địa chỉ"
    static let CONTENT00089 = "Đổi mật khẩu"
    static let CONTENT00090 = "Thoát"
    static let CONTENT00091 = "Mã"
    static let CONTENT00092 = "Trạng thái"
    static let CONTENT00093 = "Nguyên nhân"
    static let CONTENT00094 = "Nhân viên sale"
    static let CONTENT00095 = "Người tạo"
    static let CONTENT00096 = "Ngày tạo"
    static let CONTENT00097 = "Mở lại"
    static let CONTENT00098 = "Đánh giá dịch vụ"
    static let CONTENT00099 = "Danh sách bảo trì"
    static let CONTENT00100 = "Tài khoản"
    static let CONTENT00101 = "Chưa chọn hình ảnh"
    static let CONTENT00102 = "Hiện mật khẩu"
    static let CONTENT00103 = "Nội dung đánh giá &amp; góp ý"
    static let CONTENT00104 = "Khách hàng: %1$s"
    static let CONTENT00105 = "Ngày tạo: $1%s"
    static let CONTENT00106 = "%1$sID: %2$s"
    static let CONTENT00107 = "%1$s - %2$s"
    static let CONTENT00108 = "Gas Service"
    static let CONTENT00109 = "Cập nhật thông tin thành công"
    static let CONTENT00110 = "Home"
    static let CONTENT00111 = "Cài đặt"
    static let CONTENT00112 = "Bảo trì"
    static let CONTENT00113 = "Đặt Gas"
    static let CONTENT00114 = "Quản lý sự việc"
    static let CONTENT00115 = "Đăng xuất"
    static let CONTENT00121 = "Bật/Tắt Training Mode"
    static let CONTENT00122 = "Yêu cầu bảo trì"
    static let CONTENT00128	=					"Cài đặt"
    static let CONTENT00138	=					"Training mode"
    static let CONTENT00139	=					"Yêu cầu Bảo trì"
    
    static let SCREEN_WIDTH = UIScreen.mainScreen().bounds.width
    static let SCREEN_HEIGHT = UIScreen.mainScreen().bounds.height
    static let BUTTON_HEIGHT:CGFloat = 50
    static let PARENT_BORDER_WIDTH:CGFloat = 5
    static let BUTTON_BORDER_WIDTH:CGFloat = 1
    static let BUTTON_CORNER_RADIUS:CGFloat = 7
    static let STATUS_BAR_HEIGHT:CGFloat = 20
    static let NAV_BAR_HEIGHT:CGFloat = 44
    static let SEARCH_BOX_HEIGHT:CGFloat = 44
    static let POPOVER_WIDTH:CGFloat = 200
    static let LABEL_HEIGHT:CGFloat = 30
    static let CELL_HEIGHT_SHOW:CGFloat = 100
    static let CELL_HEIGHT_HIDE:CGFloat = 0
    static let BUTTON_COLOR_RED:UIColor = ColorFromRGB().getColorFromRGB(0xD5D5D5)
    static let PARENT_BORDER_COLOR_GRAY:UIColor = UIColor.grayColor()
    static let PARENT_BORDER_COLOR_YELLOW:UIColor = UIColor.yellowColor()
    static let BACKGROUND_COLOR_GRAY:UIColor = ColorFromRGB().getColorFromRGB(0xECECEC)
    
    static var TRAINING_MODE_FLAG:Bool = false
    static var LOGIN_STATUS:Bool = true
}