project '../project.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'project' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'AlamofireImage', 		'~> 3.3'
    pod 'IQKeyboardManagerSwift', 	'4.0.8'
    pod 'DLRadioButton',           	'~> 1.4'
    pod 'TagListView',                  '~> 1.2.0'
    pod 'SwiftKeychainWrapper'
end
