project '../project.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'project' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'AlamofireImage', '~> 3.3'
    
end
